# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [6]:
#### 2. Create a null vector of size 10 (★☆☆)
null=np.zeros((1,10))
print(null)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10, 49)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [23]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
np.arange(0,9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
n=[1,2,0,0,4,0] 
np.nonzero(n)

(array([0, 1, 4], dtype=int64),)

In [26]:
#### 7. Create a 3x3 identity matrix (★☆☆)
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))

array([[[0.52518735, 0.73384253, 0.96381954],
        [0.75737073, 0.44042681, 0.12061425],
        [0.23348717, 0.44381219, 0.76965437]],

       [[0.06877385, 0.07826814, 0.18407188],
        [0.96752278, 0.25702748, 0.30566946],
        [0.62016821, 0.46913532, 0.09825577]],

       [[0.90101829, 0.79930144, 0.56638283],
        [0.96354086, 0.08403644, 0.48471444],
        [0.98186206, 0.20191264, 0.6294171 ]]])

In [31]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.random((10,10))
a

array([[0.60403843, 0.11112907, 0.72158915, 0.06021596, 0.56954322,
        0.56869076, 0.44608304, 0.02598335, 0.86890786, 0.66728844],
       [0.01476519, 0.18379473, 0.59856381, 0.49855254, 0.34220432,
        0.92561418, 0.83510251, 0.58122108, 0.05038024, 0.72783674],
       [0.41212622, 0.0590148 , 0.95248533, 0.37165287, 0.85273521,
        0.82064379, 0.48668335, 0.48883412, 0.09765646, 0.68773717],
       [0.797122  , 0.67959382, 0.99213394, 0.35937956, 0.18269007,
        0.2715887 , 0.29774553, 0.7534269 , 0.52273582, 0.87904593],
       [0.45515279, 0.99697176, 0.47354926, 0.7405671 , 0.96506323,
        0.65072684, 0.06947217, 0.4243461 , 0.70917957, 0.76119449],
       [0.88279924, 0.02086368, 0.20225229, 0.73616286, 0.24702884,
        0.19804776, 0.26270098, 0.13395845, 0.96607698, 0.83028058],
       [0.95680534, 0.48032106, 0.49210622, 0.60476587, 0.9586515 ,
        0.31882846, 0.36713907, 0.99337873, 0.83011015, 0.9865807 ],
       [0.23306752, 0.40135956, 0.5893828

In [34]:
a.min()

0.014765194318069663

In [35]:
a.max()

0.9969717637451413

In [37]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
b = np.random.random((1,30))
b

array([[0.4049138 , 0.52722565, 0.12084993, 0.78915836, 0.74283941,
        0.33956875, 0.65279826, 0.63009174, 0.38382762, 0.36992339,
        0.71455219, 0.3072376 , 0.14579716, 0.46070623, 0.35399315,
        0.96312946, 0.85652356, 0.53025279, 0.73050156, 0.54664396,
        0.07716008, 0.46683479, 0.7100965 , 0.61644563, 0.25201632,
        0.22989423, 0.91571685, 0.7605875 , 0.98878955, 0.91340026]])

In [39]:
np.mean(b)

0.5500492093965489

In [58]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
d = np.diag(1+np.arange(4),k=-1)
d

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [68]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
x = np.random.random((5,5))
xmin = x.min()
xmax=x.max()
u = (x - xmin)/(xmax - xmin)
#z=(x -np.mean)/np.std
print(u)

[[0.02209213 0.40395762 0.88582856 0.98687351 0.54468941]
 [0.37882251 0.27936642 1.         0.29045709 0.12397515]
 [0.81593336 0.30819365 0.58353597 0.11063831 0.0686354 ]
 [0.92109018 0.41102355 0.23554508 0.26487739 0.72712427]
 [0.54060991 0.76048906 0.57204346 0.         0.78682533]]


In [75]:
#### 13. How to find common values between two arrays? (★☆☆)
t=np.arange(0,9).reshape((3, 3))
v=np.arange(0,4).reshape((2, 2))
f=np.intersect1d(t, v)
f

array([0, 1, 2, 3])

In [82]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
h = np.random.random((1,10))
k=np.sort(h)
k

array([[0.08545452, 0.12848935, 0.36053302, 0.38588267, 0.57237681,
        0.6116392 , 0.70250969, 0.74182081, 0.87920506, 0.97280091]])

In [101]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.37858808 0.42012208 0.1754204  0.26850051 0.91578168 0.9752581
 0.10297237 0.90145375 0.18624775 0.09614345]
Maximum value replaced by 0:
[0.37858808 0.42012208 0.1754204  0.26850051 0.91578168 0.
 0.10297237 0.90145375 0.18624775 0.09614345]


In [106]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
d=np.arange(0,9).reshape((3, 3))
print(d)
f = d - d.mean(axis=1, keepdims=True)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [112]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
c=np.random.shuffle(Z)
print(Z)
n = 5
print (x[np.argsort(c)[-n:]])

[1495 8491 2202 ... 8142 1085 9892]
[0.37858808]


In [116]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
h = np.random.random((5,3))
print(h)
s=np.where(h > 4, h, h**2)
s

[[0.08277916 0.78293942 0.95139823]
 [0.69336548 0.08310888 0.2509761 ]
 [0.15966205 0.06730454 0.92328287]
 [0.48765856 0.00768719 0.85467018]
 [0.62660003 0.14856588 0.57439233]]


array([[6.85238940e-03, 6.12994138e-01, 9.05158594e-01],
       [4.80755692e-01, 6.90708584e-03, 6.29890051e-02],
       [2.54919713e-02, 4.52990125e-03, 8.52451250e-01],
       [2.37810873e-01, 5.90928965e-05, 7.30461112e-01],
       [3.92627594e-01, 2.20718214e-02, 3.29926552e-01]])